### ISSUE TITLE
Hello! Little issue here! When I try to do double click with the mouse it doesn't select the frequency at all... How can I solve this issue?

### ISSUE THREAD

**Issue by luisa2010** [JonasKemmer/AliasFinder#10]

**Comment by JonasKemmer** [comment]
Hello Luisa,

thanks for heading out. Could you please specify which operation system and Python environment you are using?
Have you tried to run our example files?

Best,
Jonas

**Comment by JonasKemmer** [comment]
Since there was no answer for a very long time, I will close this issue.
