### ISSUE TITLE
Missing citations - [JOSS Review]

### ISSUE THREAD

**Issue by wtgee** [JonasKemmer/AliasFinder#5]
You are missing citations for the detect_peaks script you include.. While you reference them in the README they are not listed in your paper citations.  They list citation at bottom of their page: https://github.com/BMClab/BMC#how-to-cite-this-work

**Comment by StephanStock** [comment]
@wtgee If wee keep the detect_peaks and do not interchange it with the scipy version, than I will include the citation to our paper.

**Comment by JonasKemmer** [comment]
Thanks for notifying, however we decided to use [`scipy.signal.find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) according to your suggestion in [#6 ](https://github.com/JonasKemmer/AliasFinder/issues/6). The citation is therefore no longer needed.
