### ISSUE TITLE
Peak detection question - [JOSS Review]

### ISSUE THREAD

**Issue by wtgee** [JonasKemmer/AliasFinder#6]
Is there any specific reason to use the [detect_peaks](https://github.com/JonasKemmer/AliasFinder/blob/master/aliasfinder/detect_peaks.py#L11) that is used here vs e.g. [`scipy.signal.find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html)? Seems like you wouldn't have to maintain as much code and wouldn't have to be copying someone else's code into your code base. Just a suggestion.

**Comment by StephanStock** [comment]
We will have a look at this and see whether we are happy with its robustness. If so we can interchange the detect_peaks with the scipy.signal.find_peaks. Thanks for highlighting this.

**Comment by JonasKemmer** [comment]
Thanks for your suggestion, to keep the code as simple as possible we decided to implement scipy's "find_peaks" which seems to work just as fine as the other script.
